spring:
  application:
    name: service-bootcointx
  cloud:
    config:
      profile: dev
  config:
    import: optional:configserver:http://localhost:8086
    
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true